apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017